- name: Cisco versions
  hosts: cisco
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Get versions
      cisco.ios.ios_command:
        commands:
          - sh ver | include Version 1
      register: version

    - name: Get memory
      cisco.ios.ios_command:
        commands:
          - sh ver | include memory
      register: memory

    - name: Get interfaces
      cisco.ios.ios_command:
        commands:
          - sh ver | include interfaces
      register: interfaces


    - name: Show versions
      debug:
        var: version.stdout[0]

    - name: Show memory
      debug:
        var: memory.stdout[0]

    - name: Show interfaces
      debug:
        var: interfaces.stdout[0] 