- name: Cisco versions
  hosts: cisco
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Get versions
      cisco.ios.ios_command:
        commands:
          - sh ver
      register: version

    - name: Show versions
      debug:
        msg: "{{ version.stdout[0] }}"