- name: Cisco versions
  hosts: cisco
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Get versions
      cisco.ios.ios_command:
        commands:
          - sh ver | include Version 1
      register: version

    - name: Get license
      cisco.ios.ios_command:
        commands:
          - sh ver | include \*
      register: license

    - name: Show versions
      debug:
        msg:
          version: "{{ version.stdout[0] }}"


    - name: Show license
      debug:
        msg:
          license: "{{ license.stdout[0] }}"